import { spawnSync } from 'node:child_process'
import { existsSync, mkdtempSync, writeFileSync } from 'node:fs'
import { createServer } from 'node:net'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

/** Subgraph names registered in src/subgraphs/compose.yaml — the router overrides every one of them. */
export const SUBGRAPHS = ['session', 'task', 'insights', 'files'] as const

/** Composed execution config produced by `npm run compose` (gitignored, same directory). */
export const EXECUTION_CONFIG = 'router-config.json'

/**
 * Resolves the repository root — the directory the router scripts run from,
 * where `router.yaml` and the execution config live.
 *
 * @returns absolute path of the working directory (repo root)
 */
export function repoRoot(): string {
  return process.cwd()
}

/**
 * Resolves the platform-correct path of the downloaded Cosmo Router binary.
 *
 * @param root - repository root under `tools/router`
 * @returns absolute path of `router.exe` on Windows, `router` elsewhere
 */
export function routerBinaryPath(root: string): string {
  const name = process.platform === 'win32' ? 'router.exe' : 'router'
  return join(root, 'tools', 'router', name)
}

/**
 * Downloads the Cosmo Router binary through `wgc router download-binary`
 * when it is not present yet. Network-touching, so it runs only on the
 * opt-in router scripts — never inside `npm test`.
 *
 * @param root - repository root that owns `tools/router`
 * @throws {Error} when the download finishes but the binary is still missing
 */
export function ensureRouterBinary(root: string): void {
  const binary = routerBinaryPath(root)
  if (existsSync(binary)) return
  const result = spawnSync('npx', ['--yes', 'wgc@0.132.2', 'router', 'download-binary', '-o', 'tools/router'], {
    cwd: root,
    shell: true,
    stdio: 'inherit',
  })
  if (result.status !== 0 || !existsSync(binary)) {
    throw new Error('cosmo router binary download failed — run `npx --yes wgc@0.132.2 router download-binary -o tools/router` and retry')
  }
}

/**
 * Writes the router overlay so this instance reaches the subgraphs at the
 * URL of the current environment (compose.yaml itself stays pinned to
 * loopback for the hermetic CI check). Callers that need a non-default
 * listen port (the smoke run) pass `listenPort`; the overlay is loaded
 * after `router.yaml`, so its `listen_addr` wins the merge.
 *
 * @param root - repository root where `router.overrides.yaml` is written
 * @param appBaseUrl - base URL of the Atlaslink app, e.g. `http://127.0.0.1:3999`
 * @param listenPort - optional `listen_addr` port for this router instance
 */
export function writeRoutingOverrides(root: string, appBaseUrl: string, listenPort?: number): void {
  const base = appBaseUrl.replace(/\/$/, '')
  const lines = ['# Generated by src/router — do not commit (see .gitignore).']
  if (listenPort) lines.push(`listen_addr: localhost:${listenPort}`)
  lines.push('overrides:', '  subgraphs:')
  for (const name of SUBGRAPHS) {
    lines.push(`    ${name}:`, `      routing_url: ${base}/v1/graphql/${name}`)
  }
  writeFileSync(join(root, 'router.overrides.yaml'), lines.join('\n') + '\n', 'utf8')
}

/**
 * Refreshes the composed execution config from the checked-in subgraph
 * schemas so every router run serves the current graph — the same hermetic
 * `wgc` path CI uses: no token, no control plane.
 *
 * @param root - repository root where `src/subgraphs/compose.yaml` lives
 * @throws {Error} when composition fails (breaking schema change, wgc error)
 */
export function compose(root: string): void {
  const result = spawnSync('npm', ['run', 'compose'], { cwd: root, shell: true, stdio: 'inherit' })
  if (result.status !== 0) throw new Error('`npm run compose` failed — fix the composition before starting the router')
}

/**
 * Picks a free TCP port by binding to port 0 and releasing it immediately.
 *
 * @returns an ephemeral port number that was free a moment ago
 */
export function freePort(): Promise<number> {
  return new Promise((resolvePort, reject) => {
    const probe = createServer()
    probe.once('error', reject)
    probe.listen(0, '127.0.0.1', () => {
      const address = probe.address()
      const port = typeof address === 'object' && address ? address.port : 0
      probe.close(() => (port ? resolvePort(port) : reject(new Error('could not allocate a free port'))))
    })
  })
}

/**
 * Polls a URL until the predicate accepts its response, for process readiness
 * (app daemon online, router `/health/ready` answering).
 *
 * @param url - endpoint to poll
 * @param ok - predicate over the response; a thrown fetch (connection refused) counts as not-ready
 * @param label - what is being waited on, used in the timeout error
 * @param timeoutMs - give up after this long (default 30 s)
 * @throws {Error} when the endpoint never became ready in time
 */
export async function waitFor(url: string, ok: (res: Response) => boolean, label: string, timeoutMs = 30_000): Promise<void> {
  const deadline = Date.now() + timeoutMs
  let lastError = 'no response yet'
  while (Date.now() < deadline) {
    try {
      const res = await fetch(url)
      if (ok(res)) return
      lastError = `HTTP ${res.status}`
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err)
    }
    await new Promise((r) => setTimeout(r, 250))
  }
  throw new Error(`timed out waiting for ${label} (${url}): ${lastError}`)
}

/**
 * Creates an isolated temporary directory for smoke-run data (sessions and
 * workspaces never land in the developer's `data/` directory).
 *
 * @returns absolute path of the fresh directory
 */
export function makeTempDir(): string {
  return mkdtempSync(join(tmpdir(), 'atlaslink-router-smoke-'))
}
